Add mode pythonpathvenv as means of decoupling autohook venv
greenbone/autohooks pull request #76
Opened 2020-10-09 17:12 UTC by kazesberger

**What**:

This PR adds a fourth Mode `pythonpathvenv` which is different in that it writes a different shebang that points to the python executables absolute path effectively enabling any use case that might not been covered by the other modes. One (my) example is described in the **why** section below.

**Why**:

My employer uses tox (https://pypi.org/project/tox/) and there i wanted to have the possibility to add an environment for the purpose of running the autohook commands. This is at least my context.

When a user is in the development venv or global scope during development aka during authoring commits, one might not have autohook available while using `#!/usr/bin/env python3`. At least in my use case I'm using a separate venv for autohook. When i run `autohook activate` from within this venv i want it to install the hook script pointing to the venv that i've been using while running the command via tox.

**How**:

I added tests to the best of my knowledge.

**Checklist**:

- [x] Tests
- [x] [CHANGELOG](https://github.com/greenbone/autohooks/blob/master/CHANGELOG.md) Entry
- [x] Documentation

2020-10-09 18:29 UTC, y0urself approved these changes

2020-10-10 14:43 UTC, bjoernricks commented
Hi @kazesberger,

thanks a lot for your contribution. Currently I am not 100% sure what's written into the commit hook as a shebang line. Could you just give me an example?

2020-10-10 15:36 UTC, kazesberger commented
So in my tox use case it would be something like:
#!/usr/bin/env /home/user/git/project/.tox/myvenv/bin/python

Björn Ricks <notifications@github.com> schrieb am Sa., 10. Okt. 2020, 16:43:

> Hi @kazesberger <https://github.com/kazesberger>,
>
> thanks a lot for your contribution. Currently I am not 100% sure what's
> written into the commit hook as a shebang line. Could you just give me an
> example?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/greenbone/autohooks/pull/76#issuecomment-706560239>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAXET6CW663OGRF6FBTF7GLSKBXKTANCNFSM4SKKOBXA>
> .
>

2020-10-11 14:41 UTC, bjoernricks commented
> So in my tox use case it would be something like: #!/usr/bin/env /home/user/git/project/.tox/myvenv/bin/python

Ok thanks. I already thought so.

I am sorry but this doesn't make much sense. `/usr/bin/env` is to allow to use a different environment. E.g. `/usr/bin/env python` would allow to run a different python interpreter depending on the `PATH` variable of the current environment. Specifying `/usr/bin/python` instead of `/usr/bin/env python` would always require a python script to run with the system python interpreter. Thus using `/usr/bin/env` with an absolute path doesn't make sense. Also the name pythonpathenv is therefore very confusing to me. I would call it something like strict interpreter or something like that. But also I am really sure this doesn't work good for all users which fetch the git repo. Absolute paths are always eager to create issues on different systems.

2020-10-11 14:43 UTC, bjoernricks requested changes
This PR needs some rethinking. Either always a specific python installation/interpreter should be used or a virtual environment should be activated automatically before lunching the hook. Both solutions are a bit difficult to implement keeping a general solution in mind.

2020-12-21 06:34 UTC, y0urself commented
Seems to be not relevant anymore.

2020-12-21 06:34 UTC, closed without merging